[2024-12-18T19:04:05.840+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-18T19:04:05.870+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fintech_etl_pipeline.load_to_db manual__2024-12-18T19:03:40.174077+00:00 [queued]>
[2024-12-18T19:04:05.884+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fintech_etl_pipeline.load_to_db manual__2024-12-18T19:03:40.174077+00:00 [queued]>
[2024-12-18T19:04:05.885+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-18T19:04:05.911+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_to_db> on 2024-12-18 19:03:40.174077+00:00
[2024-12-18T19:04:05.927+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=157) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-18T19:04:05.932+0000] {standard_task_runner.py:72} INFO - Started process 170 to run task
[2024-12-18T19:04:05.931+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fintech_etl_pipeline', 'load_to_db', 'manual__2024-12-18T19:03:40.174077+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/fintech_dag.py', '--cfg-path', '/tmp/tmpgfif2rl9']
[2024-12-18T19:04:05.936+0000] {standard_task_runner.py:105} INFO - Job 15: Subtask load_to_db
[2024-12-18T19:04:06.045+0000] {task_command.py:467} INFO - Running <TaskInstance: fintech_etl_pipeline.load_to_db manual__2024-12-18T19:03:40.174077+00:00 [running]> on host 3053742118dc
[2024-12-18T19:04:06.158+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_engineering_team' AIRFLOW_CTX_DAG_ID='fintech_etl_pipeline' AIRFLOW_CTX_TASK_ID='load_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-12-18T19:03:40.174077+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-18T19:03:40.174077+00:00'
[2024-12-18T19:04:06.160+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-18T19:04:06.602+0000] {logging_mixin.py:190} INFO - Connected to Database
[2024-12-18T19:04:07.136+0000] {logging_mixin.py:190} INFO - Writing transformed dataset to database
[2024-12-18T19:04:19.291+0000] {logging_mixin.py:190} INFO - Done writing to database
[2024-12-18T19:04:19.298+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-18T19:04:19.320+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-18T19:04:19.322+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=fintech_etl_pipeline, task_id=load_to_db, run_id=manual__2024-12-18T19:03:40.174077+00:00, execution_date=20241218T190340, start_date=20241218T190405, end_date=20241218T190419
[2024-12-18T19:04:19.421+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-18T19:04:19.459+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-18T19:04:19.475+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
