[2024-12-19T18:24:31.222+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-19T18:24:31.238+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fintech_etl_pipeline.load_to_db manual__2024-12-19T18:24:15.930870+00:00 [queued]>
[2024-12-19T18:24:31.248+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fintech_etl_pipeline.load_to_db manual__2024-12-19T18:24:15.930870+00:00 [queued]>
[2024-12-19T18:24:31.249+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-19T18:24:31.265+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_to_db> on 2024-12-19 18:24:15.930870+00:00
[2024-12-19T18:24:31.276+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=109) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-19T18:24:31.281+0000] {standard_task_runner.py:72} INFO - Started process 122 to run task
[2024-12-19T18:24:31.278+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fintech_etl_pipeline', 'load_to_db', 'manual__2024-12-19T18:24:15.930870+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/fintech_dag.py', '--cfg-path', '/tmp/tmpg9557o9s']
[2024-12-19T18:24:31.283+0000] {standard_task_runner.py:105} INFO - Job 35: Subtask load_to_db
[2024-12-19T18:24:31.340+0000] {task_command.py:467} INFO - Running <TaskInstance: fintech_etl_pipeline.load_to_db manual__2024-12-19T18:24:15.930870+00:00 [running]> on host 2397727eff2c
[2024-12-19T18:24:31.408+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_engineering_team' AIRFLOW_CTX_DAG_ID='fintech_etl_pipeline' AIRFLOW_CTX_TASK_ID='load_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-12-19T18:24:15.930870+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-19T18:24:15.930870+00:00'
[2024-12-19T18:24:31.409+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-19T18:24:31.608+0000] {logging_mixin.py:190} INFO - Connected to Database
[2024-12-19T18:24:31.823+0000] {logging_mixin.py:190} INFO - Writing transformed dataset to database
[2024-12-19T18:24:38.611+0000] {logging_mixin.py:190} INFO - Done writing to database
[2024-12-19T18:24:38.613+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-19T18:24:38.624+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-19T18:24:38.624+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=fintech_etl_pipeline, task_id=load_to_db, run_id=manual__2024-12-19T18:24:15.930870+00:00, execution_date=20241219T182415, start_date=20241219T182431, end_date=20241219T182438
[2024-12-19T18:24:38.679+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-19T18:24:38.701+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-19T18:24:38.707+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
